---
- name: Install Apache
  hosts: all
  become: yes

  tasks:
  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ['Ubuntu', 'Debian']
  
  - name: Install Apache
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Ubuntu'