---
- name: Install Apache
  hosts: all
  become: yes

  tasks:
  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ['Ubuntu', 'Debian']
  
  - name: Install Apache and libapache2
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'